# 使用小型基础镜像
FROM 127.0.0.1:5000/bitnami/minideb:trixie.arm64

COPY add-extra-local.sh /add-extra-local.sh
# 更换软件源
RUN sed -i 's|http://deb.debian.org/debian|http://10.28.64.84:8081/repository/apt|g' /etc/apt/sources.list && \
    apt update && apt upgrade -y && \
    install_packages libfontconfig locales procps zlib1g && \
    apt-get clean && rm -rf /var/lib/apt/lists /var/cache/apt/archives
# 安装语言包
RUN localedef -c -f UTF-8 -i en_US en_US.UTF-8 && \
    update-locale LANG=C.UTF-8 LC_MESSAGES=POSIX && \
    DEBIAN_FRONTEND=noninteractive dpkg-reconfigure locales && \
    echo 'en_US.UTF-8 UTF-8' >> /etc/locale.gen && locale-gen && \
    mkdir /.local && chmod g+rwX /.local && \
    EXTRA_LOCALES="zh_CN.UTF-8 UTF-8,zh_CN.GBK GBK,zh_CN GB2312,zh_CN.GB18030 GB18030" bash /add-extra-local.sh
# 怪东西
RUN sed -i 's/^PASS_MAX_DAYS.*/PASS_MAX_DAYS    90/' /etc/login.defs && \
    sed -i 's/^PASS_MIN_DAYS.*/PASS_MIN_DAYS    0/' /etc/login.defs && \
    sed -i 's/sha512/sha512 minlen=8/' /etc/pam.d/common-password
# 设置默认时区
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo 'Asia/Shanghai' > /etc/timezone

