<?xml version="1.0" encoding="UTF-8"?>

<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>cloudcmd-auth</artifactId>
        <groupId>com.tdtech.cloudcmd</groupId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>cloudcmd-auth-service</artifactId>

    <name>cloudcmd-auth-service</name>

    <dependencies>
        <dependency>
            <groupId>com.tdtech.cloudcmd</groupId>
            <artifactId>cloudcmd-boot</artifactId>
            <version>${cloudcmd.version}</version>
            <type>pom</type>
        </dependency>
        <!--    junit      -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-compress</artifactId>
            <scope>provided</scope>
        </dependency>

        <!--    二方库   -->
        <dependency>
            <groupId>com.tdtech.cloudcmd</groupId>
            <artifactId>cloudcmd-common-util</artifactId>
            <version>${cloudcmd.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
        </dependency>
        <dependency>
            <groupId>com.tdtech.cloudcmd</groupId>
            <artifactId>cloudcmd-log</artifactId>
            <version>${cloudcmd.version}</version>
        </dependency>
        <dependency>
            <groupId>com.tdtech.cloudcmd</groupId>
            <artifactId>cloudcmd-auth-api</artifactId>
            <version>${cloudcmd.version}</version>
        </dependency>
        <dependency>
            <groupId>com.tdtech.cloudcmd</groupId>
            <artifactId>cloudcmd-im-client</artifactId>
            <version>${cloudcmd.version}</version>
        </dependency>
        <dependency>
            <groupId>com.tdtech.cloudcmd</groupId>
            <artifactId>cloudcmd-im-api</artifactId>
            <version>${cloudcmd.version}</version>
        </dependency>
        <dependency>
            <groupId>com.tdtech.cloudcmd</groupId>
            <artifactId>cloudcmd-spring-boot-starter-web</artifactId>
            <version>${cloudcmd.version}</version>
        </dependency>
        <dependency>
            <groupId>com.tdtech.cloudcmd</groupId>
            <artifactId>cloudcmd-common-license</artifactId>
            <version>${cloudcmd.version}</version>
        </dependency>
        <dependency>
            <groupId>com.tdtech.cloudcmd</groupId>
            <artifactId>cloudcmd-redis-starter</artifactId>
            <version>${cloudcmd.version}</version>
        </dependency>

        <!--        lombok      -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>

        <!--                spring cloud    -->
        <dependency>
            <groupId>com.tdtech.cloudcmd</groupId>
            <artifactId>cloudcmd-dubbo-starter</artifactId>
            <version>${cloudcmd.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-commons</artifactId>
        </dependency>
        <!--        spring boot -->
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-pool2</artifactId>
        </dependency>
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
        </dependency>
<!--        <dependency>-->
<!--            <groupId>org.mybatis.spring.boot</groupId>-->
<!--            <artifactId>mybatis-spring-boot-starter</artifactId>-->
<!--        </dependency>-->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-jdbc</artifactId>
        </dependency>
        <dependency>
            <groupId>commons-collections</groupId>
            <artifactId>commons-collections</artifactId>
        </dependency>
        <dependency>
            <groupId>com.tdtech.cloudcmd</groupId>
            <artifactId>cloudcmd-common-i18n</artifactId>
            <version>${cloudcmd.version}</version>
        </dependency>
        <dependency>
            <groupId>jakarta.ws.rs</groupId>
            <artifactId>jakarta.ws.rs-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpmime</artifactId>
        </dependency>

        <dependency>
            <groupId>com.tdtech.cloudcmd</groupId>
            <artifactId>cloudcmd-msip</artifactId>
            <version>${cloudcmd.version}</version>
        </dependency>
        <dependency>
            <groupId>com.tdtech.cloudcmd</groupId>
            <version>1.0.0-SNAPSHOT</version>
            <artifactId>cloudcmd-admin-api</artifactId>
        </dependency>
        <dependency>
            <groupId>com.tdtech.cloudcmd</groupId>
            <version>1.0.0-SNAPSHOT</version>
            <artifactId>cloudcmd-es-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>com.tdtech.cloudcmd</groupId>
            <artifactId>linkx-dashboard-api</artifactId>
            <version>${cloudcmd.version}</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>${spring.boot.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
