<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>micronaut-parent</artifactId>
        <groupId>io.micronaut.platform</groupId>
        <version>4.9.3</version>
    </parent>
    <artifactId>cloudcmd-script</artifactId>
    <groupId>com.tdtech.cloudcmd.script</groupId>
    <modelVersion>4.0.0</modelVersion>
    <packaging>${packaging}</packaging>
    <version>0.1</version>
    <properties>
        <exec.mainClass>com.tdtech.cloudcmd.script.Application</exec.mainClass>
        <graaljs.version>24.2.2</graaljs.version>
        <jdk.version>21</jdk.version>
        <micronaut.aot.enabled>true</micronaut.aot.enabled>
        <micronaut.aot.packageName>com.tdtech.cloudcmd.script.aot.generated</micronaut.aot.packageName>
        <micronaut.runtime>netty</micronaut.runtime>
        <micronaut.version>4.9.2</micronaut.version>
        <packaging>jar</packaging>
        <release.version>21</release.version>
    </properties>
    <build>
        <plugins>
            <plugin>
                <artifactId>micronaut-maven-plugin</artifactId>
                <configuration>
                    <configFile>aot-${packaging}.properties</configFile>
                </configuration>
                <groupId>io.micronaut.maven</groupId>
            </plugin>
            <plugin>
                <artifactId>maven-enforcer-plugin</artifactId>
                <groupId>org.apache.maven.plugins</groupId>
            </plugin>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <annotationProcessorPaths combine.children="append">
                        <path>
                            <artifactId>micronaut-http-validation</artifactId>
                            <groupId>io.micronaut</groupId>
                            <version>${micronaut.core.version}</version>
                        </path>
                        <path>
                            <artifactId>micronaut-serde-processor</artifactId>
                            <exclusions>
                                <exclusion>
                                    <artifactId>micronaut-inject</artifactId>
                                    <groupId>io.micronaut</groupId>
                                </exclusion>
                            </exclusions>
                            <groupId>io.micronaut.serde</groupId>
                            <version>${micronaut.serialization.version}</version>
                        </path>
                        <path>
                            <artifactId>micronaut-openapi</artifactId>
                            <groupId>io.micronaut.openapi</groupId>
                            <version>${micronaut.openapi.version}</version>
                        </path>
                        <path>
                            <artifactId>micronaut-data-processor</artifactId>
                            <groupId>io.micronaut.data</groupId>
                            <version>${micronaut.data.version}</version>
                        </path>
                    </annotationProcessorPaths>
                    <compilerArgs>
                        <arg>-Amicronaut.processing.group=com.tdtech.cloudcmd.script</arg>
                        <arg>-Amicronaut.processing.module=cloudcmd-script</arg>
                    </compilerArgs>
                </configuration>
                <groupId>org.apache.maven.plugins</groupId>
            </plugin>
        </plugins>
    </build>
    <dependencies>
        <dependency>
            <artifactId>micronaut-http-server-netty</artifactId>
            <groupId>io.micronaut</groupId>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <artifactId>micronaut-serde-jackson</artifactId>
            <groupId>io.micronaut.serde</groupId>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <artifactId>micronaut-validation</artifactId>
            <groupId>io.micronaut.validation</groupId>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <artifactId>jakarta.validation-api</artifactId>
            <groupId>jakarta.validation</groupId>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <artifactId>micronaut-reactor</artifactId>
            <groupId>io.micronaut.reactor</groupId>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <artifactId>micronaut-kafka</artifactId>
            <groupId>io.micronaut.kafka</groupId>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <artifactId>micronaut-data-processor</artifactId>
            <groupId>io.micronaut.data</groupId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <artifactId>micronaut-data-r2dbc</artifactId>
            <groupId>io.micronaut.data</groupId>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-core</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <artifactId>r2dbc-mysql</artifactId>
            <groupId>io.asyncer</groupId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <artifactId>snakeyaml</artifactId>
            <groupId>org.yaml</groupId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <artifactId>micronaut-http-client</artifactId>
            <groupId>io.micronaut</groupId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <artifactId>micronaut-test-junit5</artifactId>
            <groupId>io.micronaut.test</groupId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <artifactId>junit-jupiter-api</artifactId>
            <groupId>org.junit.jupiter</groupId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <artifactId>junit-jupiter-engine</artifactId>
            <groupId>org.junit.jupiter</groupId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <artifactId>js-scriptengine</artifactId>
            <groupId>org.graalvm.js</groupId>
            <version>${graaljs.version}</version>
        </dependency>
        <dependency>
            <artifactId>js-community</artifactId>
            <groupId>org.graalvm.polyglot</groupId>
            <type>pom</type>
            <version>${graaljs.version}</version>
        </dependency>
    </dependencies>


</project>
