<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.chinasoft.cloud</groupId>
        <artifactId>crs-module-ai-agent</artifactId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>crs-module-ai-agent-server</artifactId>
    <packaging>jar</packaging>

    <name>${project.artifactId}</name>
    <properties>
        <graaljs.version>24.2.2</graaljs.version>
    </properties>
    <dependencies>
        <!-- Spring Cloud 基础 -->
        <dependency>
            <groupId>com.chinasoft.cloud</groupId>
            <artifactId>crs-spring-boot-starter-env</artifactId>
        </dependency>

        <!-- 依赖服务 -->

        <!-- 业务组件 -->
        <dependency>
            <groupId>com.chinasoft.cloud</groupId>
            <artifactId>crs-spring-boot-starter-biz-data-permission</artifactId>
        </dependency>
        <dependency>
            <groupId>com.chinasoft.cloud</groupId>
            <artifactId>crs-spring-boot-starter-biz-tenant</artifactId>
        </dependency>
        <dependency>
            <groupId>com.chinasoft.cloud</groupId>
            <artifactId>crs-spring-boot-starter-biz-ip</artifactId>
        </dependency>

        <!-- Web 相关 -->
        <dependency>
            <groupId>com.chinasoft.cloud</groupId>
            <artifactId>crs-spring-boot-starter-security</artifactId>
        </dependency>

        <!-- DB 相关 -->
        <dependency>
            <groupId>com.chinasoft.cloud</groupId>
            <artifactId>crs-spring-boot-starter-mybatis</artifactId>
        </dependency>

        <dependency>
            <groupId>com.chinasoft.cloud</groupId>
            <artifactId>crs-spring-boot-starter-redis</artifactId>
        </dependency>

        <!-- RPC 远程调用相关 -->
        <dependency>
            <groupId>com.chinasoft.cloud</groupId>
            <artifactId>crs-spring-boot-starter-rpc</artifactId>
        </dependency>

        <!-- Registry 注册中心相关 -->
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        </dependency>

        <!-- Config 配置中心相关 -->
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
        </dependency>

        <!-- Job 定时任务相关 -->
        <!--        <dependency>-->
        <!--            <groupId>com.chinasoft.cloud</groupId>-->
        <!--            <artifactId>crs-spring-boot-starter-job</artifactId>-->
        <!--        </dependency>-->


        <!--        &lt;!&ndash; 监控相关 &ndash;&gt;-->
        <dependency>
            <groupId>com.chinasoft.cloud</groupId>
            <artifactId>crs-spring-boot-starter-monitor</artifactId>
        </dependency>

        <dependency>
            <groupId>com.chinasoft.cloud</groupId>
            <artifactId>crs-module-ai-agent-api</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>com.chinasoft.cloud</groupId>
            <artifactId>crs-module-infra-api</artifactId>
            <version>${revision}</version>
        </dependency>

        <dependency>
            <groupId>com.chinasoft.cloud</groupId>
            <artifactId>crs-spring-boot-starter-excel</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <artifactId>js-scriptengine</artifactId>
            <groupId>org.graalvm.js</groupId>
            <version>${graaljs.version}</version>
        </dependency>
        <dependency>
            <artifactId>js-community</artifactId>
            <groupId>org.graalvm.polyglot</groupId>
            <type>pom</type>
            <version>${graaljs.version}</version>
        </dependency>
    </dependencies>

    <build>
        <!-- 设置构建的 jar 包名 -->
        <finalName>${project.artifactId}</finalName>
        <plugins>
            <!-- 打包 -->
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>${spring.boot.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal> <!-- 将引入的 jar 打入其中 -->
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
