---
# Source: web/templates/cm.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: linkx
  name: cloudcmd-admin-web-config
data:
  cloud.admin.conf: |-
    server{
        listen       8012;
  
        location /{
            if ($request_method = 'OPTIONS') {
                return 200;
            }
            alias /usr/share/nginx/html/;
            index index.html index.htm login.html;
            try_files $uri $uri/ /index.html;
            proxy_set_header x-forwarded-for $remote_addr;
        }
    }
---
# Source: web/templates/service.yaml
kind: Service
apiVersion: v1
metadata:
  namespace: linkx
  name: cloudcmd-admin-web
  labels:
    app.kubernetes.io/name: cloudcmd-admin-web
spec:
  selector:
    app: cloudcmd-admin-web
  ports:
    - port: 8012
      name: web
      protocol: TCP
      targetPort: 8012
---
# Source: web/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: linkx
  name: cloudcmd-admin-web
  labels:
    app: cloudcmd-admin-web
    app.kubernetes.io/name: cloudcmd-admin-web
    ha-service-stop/enable: "true"
spec:
  selector:
    matchLabels:
      app: cloudcmd-admin-web
  replicas: 1
  template:
    metadata:
      name: cloudcmd-admin-web
      labels:
        app: cloudcmd-admin-web
        app.kubernetes.io/name: cloudcmd-admin-web
        enableRestart: "true"
      annotations:
        helm.sh/chart: web-0.1.0
        app.kubernetes.io/name: cloudcmd-admin-web
        app.kubernetes.io/instance: cloudcmd-admin-web
        app.kubernetes.io/version: "1.16.0"
        app.kubernetes.io/managed-by: Helm
    spec:
      volumes:
        - name: cloudcmd-admin-web-config
          configMap:
            name: cloudcmd-admin-web-config
      containers:
        - name: cloudcmd-admin-web
          image: imagerepo.td-tech.com:5001/cloudcmd-admin-web:{Version}.{Arch}.{BuildTime}
          imagePullPolicy: Always
          ports:
            - name: web
              containerPort: 8012
          volumeMounts:
            - name: cloudcmd-admin-web-config
              mountPath: /etc/nginx/conf.d/
