#!/bin/bash

dir_ccmd=ccmd
dir_icc=web
dir_admin=cloudcmd-admin-web
dir_h5portal=H5Portal

curr_dir=$(pwd)
export path_workspace=$(cd $(dirname ${BASH_SOURCE[0]})/; pwd)
cd ${curr_dir}
export path_tool=${path_workspace}/autoinstall_tool
export path_pkg=${path_workspace}/build/ccmd

register_host=imagerepo.td-tech.com:5001
#pkg_ver=V100R001C00SPC120B003
pkg_ver=$(grep "version_internal_id" ${path_workspace}/meta/app-info-linkx.yaml | egrep -o "V[0-9]{3}+R[0-9]{3}C[0-9]{2}[SPCB0-9]*")
prd_name=LINKX
Arch=x86
arch=${Arch}
patch_target=job-db
action=package

USER_INFO_FILE=${path_workspace}/global_user_info.json
gitee_repo=$(python3 -c "import sys, json; print(json.load(open('${USER_INFO_FILE}'))['VERSION_PACKAGE']['Linkx']['Gitee']['GiteeREPO'])")
gitee_api_token=$(python3 -c "import sys, json; print(json.load(open('${USER_INFO_FILE}'))['VERSION_PACKAGE']['Linkx']['Gitee']['GiteeAPIToken'])")
gitee_backup=$(python3 -c "import sys, json; print(json.load(open('${USER_INFO_FILE}'))['VERSION_PACKAGE']['Linkx']['Gitee']['GiteeBackUP'])")
