apiVersion: apps/v1
kind: Deployment
metadata:
  name: mapbox
  namespace: {{ .Values.namespace }}
  labels:
    app: mapbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mapbox
  template:
    metadata:
      name: mapbox
      labels:
        app: mapbox
        {{- if and .Values.enableRestart (eq .Values.enableRestart "true") }}
        enableRestart: "true"
        {{- end }}
    spec:
      containers:
        - name: mapbox
          image: {{ .Values.imageName | default (printf "%s/%s:%s" .Values.image.registry "mapbox" .Values.image.tag) }}
          imagePullPolicy: Always
          command:
            - java
          args:
            - -jar
            - -Xms1g
            - -Xmx3g
            - -XX:+UnlockExperimentalVMOptions
            - /opt/offlinemap/map-offline-server-1.0.2-SNAPSHOT.jar
          livenessProbe:
            tcpSocket:
              port: 10101
            initialDelaySeconds: 60
            timeoutSeconds: 5
            failureThreshold: 3
            periodSeconds: 20
          readinessProbe:
            tcpSocket:
              port: 10101
            initialDelaySeconds: 60
            timeoutSeconds: 5
            failureThreshold: 3
            periodSeconds: 20
          volumeMounts:
            - mountPath: /home/ics/offlinemap/data
              name: mapbox-store
      volumes:
        - name: mapbox-store
          persistentVolumeClaim:
            claimName: mapbox-store-pvc-claim
      restartPolicy: Always