<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>cloudcmd-service</artifactId>
        <groupId>com.tdtech.cloudcmd</groupId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>cloudcmd-im</artifactId>
    <packaging>pom</packaging>
    <modules>
<!--        <module>cloudcmd-im-record-service</module>-->
        <module>cloudcmd-im-jingxin</module>
        <module>cloudcmd-im-openapi</module>
        <module>cloudcmd-im-client</module>
        <module>cloudcmd-im-api</module>
    </modules>

</project>