apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-appinfo-copy-cm
  namespace: platform
  labels:
    app: agent-appinfo-copy-cm
data:
  copy.sh: |
    #!/bin/sh
    mkdir -p /opt/version/agent
    #拷贝版本信息
    cp /opt/deploy/agent/app-info.yaml /opt/version/agent/app-info.yaml
    echo 'Copy file finished'
    sleep 2
    curl -X PUT http://msip-service:8445/msip/cmcenter/reloadMenu
---
apiVersion: batch/v1
kind: Job
metadata:
  name: agent-appinfo-copy-{{ .Values.now }}
  namespace: platform
spec:
  template:
    metadata:
      name: agent-appinfo-copy
    spec:
      restartPolicy: Never
      containers:
        - name: agent-appinfo-copy
          image: imagerepo.td-tech.com:5001/busybox-curl:7.79.1.0
          imagePullPolicy: Always
          command:
            - /opt/copy.sh
          volumeMounts:
            - name: shell
              mountPath: /opt/copy.sh
              subPath: copy.sh
            - name: versionpv
              mountPath: /opt/version
            - name: source
              mountPath: /opt/deploy/agent/
      volumes:
        - name: shell
          configMap:
            name: agent-appinfo-copy-cm
            defaultMode: 0700
        - name: source
          hostPath:
            path: /data/install/agent/
        - name: versionpv
          persistentVolumeClaim:
            claimName: version-pvc