apiVersion: v1
kind: ConfigMap
metadata:
  namespace: agent
  name: ha-mediary-conf-agent
  labels:
    type: ha-mediary-conf
data:
  ha-mediary-conf-agent: |
    - namespace: agent
      failCount: 24