---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: agent
  name: mock-ai
  labels:
    app: mock-ai
spec:
  replicas: 1
  template:
    metadata:
      name: mock-ai
      labels:
        app: mock-ai
    spec:
      volumes:
        - name: agent-profile
          configMap:
            name: agent-profile
            items:
              - key: application.yml
                path: application.yml
      containers:
        - name: mock-ai
          image: imagerepo.td-tech.com:5001/mock-ai:{{ .Values.version }}.{{ .Values.arch }}
          command: [ 'java' ]
          args:
            - -jar
            - -Dfile.encoding=UTF-8
            - -Xmx2048m
            - -Xms256m
            - -XX:+UseZGC
            - -XX:+ZGenerational
            - -Dserver.port=8080
            - -Dspring.profiles.active=prod
            - /app/app.jar
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: agent-profile
              mountPath: /app/config/
          readinessProbe:
            failureThreshold: 12
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
          livenessProbe:
            failureThreshold: 6
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
          env:
            - name: NACOS_ADDRESS
              value: nacos.platform:8848
            - name: NACOS_GROUP
              value: agent
            - name: MYSQL_HOST
              value: cnp-leader.platform.svc
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USER
              value: cnp
            - name: MYSQL_PASSWORD
              value: safebox:platform/platform-secret#mysql_password
            - name: REDIS_HOST
              value: redis.platform.svc
            - name: REDIS_POST
              value: "6379"
            - name: REDIS_PASSWORD
              value: safebox:platform/platform-secret#redis_password
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka-service.platform.svc.cluster.local:9092
            - name: cloudcmd.service.name
              value: mock-ai
            - name: SERVER_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: pod.ip
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: pod.name
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
      restartPolicy: Always
  selector:
    matchLabels:
      app: mock-ai
---
apiVersion: v1
kind: Service
metadata:
  namespace: agent
  name: mock-ai
spec:
  selector:
    app: mock-ai
  ports:
    - port: 8080
      name: http
      protocol: TCP
      targetPort: 8080