package com.tdtech.cloudcmd.admin.resource.resourceConstants;

import java.util.Arrays;
import java.util.List;

/**
 * 常量
 */
public interface Constants {

    String IMPORT_DATA_USERID_LOCK = "cloudcmd:import:userId:importDataUserIdLock";

    // Map Type
    String DEVICE_RESOLUTION_RATIO = "DEVICE_RESOLUTION_RATIO";
    String P720 = "720P";
    String P1080 = "1080P";
    String K2 = "2K";
    String K4 = "4K";
    String MAP_TYPE = "MAP_TYPE";
    String SUPER_MAP = "SuperMap";
    String AMap = "AMap";
    String MapAbc = "MapAbc";
    String ARCGIS_MAP = "ArcgisMap";
    String MineMap = "MineMap";

    List<String> MAP_TYPES = Arrays.asList(SUPER_MAP, AMap, ARCGIS_MAP, MapAbc, MineMap);
    List<String> DEVICE_RESOLUTION_RATIOS = Arrays.asList(P720, P1080, K2, K4);

    // IP 配置项 名称
    String CAGENT_IP = "CAGENT_IP";
    String SDK_IP = "SDK_IP";
    String MAP_IP = "MAP_IP";

    List<String> IP_TYPES = Arrays.asList(CAGENT_IP, SDK_IP, MAP_IP);

    String CAGENT_PORT = "CAGENT_PORT";
    String SDK_PORT = "SDK_PORT";
    String DEFAULT_ZOOM = "DEFAULT_ZOOM";
    String MIN_ZOOM = "MIN_ZOOM";
    String MAX_ZOOM = "MAX_ZOOM";
    String AUTH_AUTO_UNLOCK_TIME = "AUTH_AUTO_UNLOCK_TIME";
    String AUTH_LOGIN_ERROR_NUM_LIMIT = "AUTH_LOGIN_ERROR_NUM_LIMIT";
    String AUTH_PWD_VALIDITY_PERIOD = "AUTH_PWD_VALIDITY_PERIOD";
    String AUTH_TOKEN_EXPIRE_IN = "AUTH_TOKEN_EXPIRE_IN";
    String AUTH_REFRESHTOKEN_EXPIRE_IN = "AUTH_REFRESHTOKEN_EXPIRE_IN";
    String CAPP_LOCATION_RESOURCE_CAN_SEE_DISTANCE = "CAPP_LOCATION_RESOURCE_CAN_SEE_DISTANCE";
    String CAPP_TASK_CAN_SEE_CAMERA_DISTANCE = "CAPP_TASK_CAN_SEE_CAMERA_DISTANCE";
    String CAPP_TASK_CAN_OPERATOR_CAMERA_DISTANCE = "CAPP_TASK_CAN_OPERATOR_CAMERA_DISTANCE";
    String REFRESH_TIME = "REFRESH_TIME";
    String MAP_REFRESH_PERIOD = "MAP_REFRESH_PERIOD";

    String MSIP_DISK_SAFE_SIZE = "MSIP_DISK_SAFE_SIZE";

    String DUTY_SCHEDULE_NOTICE_PERIOD = "DUTY_SCHEDULE_NOTICE_PERIOD";

    String DUTY_SCHEDULE_NOTICE_COUNT = "DUTY_SCHEDULE_NOTICE_COUNT";

    List<String> RANGE_TYPES = Arrays.asList(CAGENT_PORT, SDK_PORT, DEFAULT_ZOOM, MIN_ZOOM, MAX_ZOOM,
        AUTH_AUTO_UNLOCK_TIME, AUTH_LOGIN_ERROR_NUM_LIMIT, AUTH_PWD_VALIDITY_PERIOD, AUTH_TOKEN_EXPIRE_IN,
        AUTH_REFRESHTOKEN_EXPIRE_IN, CAPP_LOCATION_RESOURCE_CAN_SEE_DISTANCE, CAPP_TASK_CAN_SEE_CAMERA_DISTANCE,
        CAPP_TASK_CAN_OPERATOR_CAMERA_DISTANCE, REFRESH_TIME, MAP_REFRESH_PERIOD, MSIP_DISK_SAFE_SIZE, DUTY_SCHEDULE_NOTICE_PERIOD, DUTY_SCHEDULE_NOTICE_COUNT);

    // IP 配置项 名称
    String AUTH_FIRSTLOGIN_FORCE_CHANGEPWD = "AUTH_FIRSTLOGIN_FORCE_CHANGEPWD";
    String AUTH_MULTI_END_LOGIN_ALLOWED = "AUTH_MULTI_END_LOGIN_ALLOWED";
    List<String> BOOLEAN_FIXVALUE_TYPES = Arrays.asList(AUTH_FIRSTLOGIN_FORCE_CHANGEPWD, AUTH_MULTI_END_LOGIN_ALLOWED);

    String AUTO_MISSION_STATUS = "AUTO_MISSION_STATUS";
    String VIDEO_OFFER = "VIDEO_OFFER";
    String EDGEGATEWAY_BREAKER = "EDGEGATEWAY_BREAKER";
    String CAR_BREAKER = "CAR_BREAKER";
    String CUSTOMIZED_LAYER = "CUSTOMIZED_LAYER";
    String APPLICATION_BREAKER = "APPLICATION_BREAKER";
    String CAR_TYPE = "CAR_TYPE";
    String SUSPECT_IN = "SUSPECT_IN";
    String CAPABILITY_SWITCH = "CAPABILITY_SWITCH";
    String SUSPECTTASK_OFFLINE_SWITCH = "SUSPECTTASK_OFFLINE_SWITCH";
    String AI_SEPARATED_DEPLOY = "AI_SEPARATED_DEPLOY";
    String GROUP_AI_HOST = "GROUP_AI_HOST";
    String GROUP_AI_FRONTEND_HOST = "GROUP_AI_FRONTEND_HOST";
    List<String> FIXVALUE_TYPES = Arrays.asList(AUTO_MISSION_STATUS, VIDEO_OFFER, EDGEGATEWAY_BREAKER, CAR_BREAKER,
        CUSTOMIZED_LAYER, APPLICATION_BREAKER, SUSPECT_IN, CAPABILITY_SWITCH, SUSPECTTASK_OFFLINE_SWITCH,
        AI_SEPARATED_DEPLOY);

    String TRUE = "true";
    String FALSE = "false";

    String STATION_NAME = "STATION_NAME";
    String CORE_CIRCLE_RADIUS_ONE = "CORE_CIRCLE_RADIUS_ONE";
    String CORE_CIRCLE_RADIUS_TWO = "CORE_CIRCLE_RADIUS_TWO";
    String CORE_CIRCLE_RADIUS_THREE = "CORE_CIRCLE_RADIUS_THREE";

    List<String> CORE_CIRCLE_RADIUS_TYPES =
        Arrays.asList(CORE_CIRCLE_RADIUS_ONE, CORE_CIRCLE_RADIUS_TWO, CORE_CIRCLE_RADIUS_THREE);
    String STATION_NAME_CHINESE = "STATION_NAME_CHINESE";
    String REFRESH_OVERSPEED_LIST = "REFRESH_OVERSPEED_LIST";
    String STATISTICS_REFRESH_TIME = "STATISTICS_REFRESH_TIME";
    List<String> GLOBALS_VALUE_EMPTY = Arrays.asList("GROUP_CREATE_FUN_ONE_KEY_NAME", "GROUP_CREATE_ONE_KEY_DISPATCH_USERS", GROUP_AI_FRONTEND_HOST);

}
