order: 50400
rollback_order: 50400
name: pvc
error_ignore: false
gather_facts: false
handler_host: kube_control_plane
always_exec_upgrade: true
always_exec_rollback: true
phases:
  - install
  - upgrade
  - rollback  
