version_package_name = linkx.tar.gz
extended_ne_dir_name = linkx_upgrade
backup_dbs_conf = backup_dbs.conf
backup_files_conf = backup_files.conf
backup_files_conf_host = backup_files_host.conf
backup_nacos_conf = backup_nacos.conf
stop_services_shell = stop_svc.sh
start_services_shell = start_svc.sh
upgrade_pre_handle_shell = upgrade_pre_handle.sh
upgrade_post_handle_shell = upgrade_post_handle.sh
degrade_pre_handle_shell = degrade_pre_handle.sh
degrade_post_handle_shell = degrade_post_handle.sh
version_info_xml = app_info.yml