FROM repo.rd.td-tech.com/docker-virtual/linkx/msip/jre:11.openeuler.openjre.arm64
# 复制版本信息文件和jar包
COPY ./version.ini /app/version.ini
COPY ./linkx-node-service-1.0.0-SNAPSHOT.jar /app/app.jar
# 设置工作目录
WORKDIR /app
# 执行命令
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app/app.jar"]
