order: 50300
rollback_order: 50300
name: images
handler_host: kube_control_plane
error_ignore: false
gather_facts: false
always_exec_upgrade: true
always_exec_rollback: true
phases:
  - install
  - upgrade
  - rollback  
  - patch_install 
  - patch_rollback