order: 50000
name: backup_db
error_ignore: false
gather_facts: false
handler_host: kube_control_plane
always_exec_upgrade: true
phases:
  - upgrade
  - patch_install
models:
  - standalone
  - three_nodes
  - multi_nodes