# 该镜像需要依赖的基础镜像
FROM repo.rd.td-tech.com/docker-virtual/linkx/nginx:1.29.4-alpine3.23-slim.amd64
# 设置作者
MAINTAINER ics
# 复制文件到容器中
COPY cloudcmd /usr/share/nginx/html/
COPY images /usr/share/nginx/html/images
# 声明服务运行端口
EXPOSE 8080
# 执行命令
ENTRYPOINT ["nginx", "-g", "daemon off;"]
