haControl: "true"
ports:
  - name: http
    port: 8080
  - name: dubbo
    port: 18080
container:
  strategy:
  replicas: 1
  vault: true
  volumes:
    - pvc: headshot-store
      mount_path: /home/linkx/headshot/
    - pvc: log-store
      mount_path: /home/ubp/log_store/
    - pvc: jingxin-file
      mount_path: /home/linkx/file/
    - pvc: mapbox-store
      mount_path: /home/ics/offlinemap/data
  envs:
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: safebox:platform/platform-secret#mysql_password
      - name: REDIS_PASSWORD
        value: safebox:platform/platform-secret#redis_password
    env_from:
      - configMapRef:
          name: cloudcmd-profile
  jvm:
    xmx: 3g
    xms: 3g
