<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.chinasoft.cloud</groupId>
        <artifactId>crs</artifactId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <modules>
        <module>crs-module-ai-agent-server</module>
        <module>crs-module-ai-agent-api</module>
    </modules>
    <artifactId>crs-module-ai-agent</artifactId>
    <packaging>pom</packaging>

    <name>${project.artifactId}</name>
    <description>
        ai 代理
    </description>

</project>
