---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: agent
  name: agent-web-config
data:
  agent.web.conf: |-

    limit_conn_zone $host zone=server_conn:10m;

    server{
        listen 8081;
        location /{
            alias /usr/share/nginx/html/;
            try_files $uri $uri/ /index.html;
        }
    
        add_header Referrer-Policy "no-referrer";
        add_header X-Download-Options 'noopen';
        add_header X-XSS-Protection '1;mode=block';
        add_header X-Frame-Options SAMEORIGIN;
        add_header X-Content-Type-Options 'nosniff';
        add_header Strict-Transport-Security 'max-age=15552000';
        add_header X-Permitted-Cross-Domain-Policies 'none';
    }
---
kind: Service
apiVersion: v1
metadata:
  namespace: agent
  name: agent-web
spec:
  selector:
    app: agent-web
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      name: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: agent
  name: agent-web
  labels:
    app.kubernetes.io/name: agent-web
    ha-service-stop/enable: "true"
spec:
  selector:
    matchLabels:
      app: agent-web
  replicas: 1
  template:
    metadata:
      labels:
        app: agent-web
        app.kubernetes.io/name: agent-web
        enableRestart: "true"
    spec:
      volumes:
        - name: agent-web-config
          configMap:
            name: agent-web-config
        - name: download
          hostPath:
            path: /home/agent/download
      containers:
        - name: agent-web
          image: imagerepo.td-tech.com:5001/agent-web:{{ .Values.version }}.{{ .Values.arch }}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8081
          volumeMounts:
            - name: agent-web-config
              mountPath: /etc/nginx/conf.d/
              readOnly: true
            - name: download
              mountPath: /usr/share/nginx/html/download/