apiVersion: v1
kind: ConfigMap
metadata:
  namespace: linkx
  name: linkx-encryptor-config
data:
  BZ_SERVER_ID: "bz_server.oo"
  BZ_DEVICE_ID: "1A-2B-3C-4D-5E-6F"
  ENCRYPT_TYPE: "SDK"
  HTTP_CONNECTOR: "false"
  SDK_ENV: "dev"
  SM_HOST: "https://dev-ucpsapi.pimse.gab.ydxxw:10160/scm-api"
  SM_SECRET: "secret_dev"
---
apiVersion: v1
kind: Service
metadata:
  namespace: linkx
  name: linkx-encryptor-service
  labels:
    app.kubernetes.io/name: linkx-encryptor-service
spec:
  selector:
    app: linkx-encryptor-service
  ports:
    - port: 9090
      name: healthz
      protocol: TCP
      targetPort: 9090
    - port: 8080
      name: http
      protocol: TCP
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: actuator-prometheus-linkx-encryptor-service
  namespace: linkx
  annotations:
    platform.prometheus: "/actuator/prometheus"
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: 9090
      name: metrics
  selector:
    app: linkx-encryptor-service
---
# Source: springboot-server/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: linkx
  name: linkx-encryptor-service
  labels:
    app: linkx-encryptor-service
    app.kubernetes.io/name: linkx-encryptor-service
    ha-service-stop/enable: "true"
spec:
  replicas: 1
  template:
    metadata:
      name: linkx-encryptor-service
      labels:
        app: linkx-encryptor-service
        app.kubernetes.io/name: linkx-encryptor-service
        enableRestart: "true"
      annotations:
        helm.sh/chart: springboot-server-0.1.0
        app.kubernetes.io/name: linkx-encryptor-service
        app.kubernetes.io/instance: linkx-encryptor-service
        app.kubernetes.io/version: "1.16.0"
        app.kubernetes.io/managed-by: Helm
        safebox/enable: "true"
    spec:
      hostAliases:
        - ip: "114.113.233.109"
          hostnames:
            - "dev-ucpsapi.pimse.gab.ydxxw"
      volumes:
        - name: linkx-encryptor-service-headshot-store
          persistentVolumeClaim:
            claimName: headshot-store-pvc-claim
        - name: linkx-encryptor-service-log-store
          persistentVolumeClaim:
            claimName: log-store-pvc-claim
        - name: linkx-encryptor-service-jingxin-file
          persistentVolumeClaim:
            claimName: jingxin-file-pvc-claim
        - name: linkx-encryptor-service-mapbox-store
          persistentVolumeClaim:
            claimName: mapbox-store-pvc-claim
        - name: oom-dump
          persistentVolumeClaim:
            claimName: oom-dump-pvc-claim

      initContainers:
        - name: wait-zookeeper
          image: imagerepo.td-tech.com:5001/busybox:1.28.0
          imagePullPolicy: Always
          command: [ 'sh', '-c', "until nc -z -v -w 20 zookeeper-0.zookeeper 2181; do echo waiting for zookeeper-0.zookeeper 2181; sleep 6; done" ]
      containers:
        - name: linkx-encryptor-service
          image: imagerepo.td-tech.com:5001/linkx-encryptor-service:{Version}.{Arch}.{BuildTime}
          
          command: [ 'sh', '-c' ]
          args:
            - |
              keytool -import -cacerts -storepass changeit -noprompt -alias jx-ca -file /app/sm.crt || true
              java -jar \
                -Dfile.encoding=UTF-8 \
                -Duser.timezone=Asia/Shanghai \
                -Xmx3g \
                -Xms3g \
                -server \
                -XX:+UseG1GC \
                -XX:+UseStringDeduplication \
                -XX:MaxGCPauseMillis=20 \
                -XX:InitiatingHeapOccupancyPercent=50 \
                -XX:G1HeapWastePercent=10 \
                -XX:+ExplicitGCInvokesConcurrent \
                -XX:MaxInlineLevel=15 \
                -verbose:gc \
                -XX:+PrintGCDetails \
                -XX:+HeapDumpOnOutOfMemoryError \
                -XX:HeapDumpPath=/opt/dump/linkx-encryptor-service.dump \
                -XX:+UnlockExperimentalVMOptions \
                -Djdk.internal.httpclient.disableHostnameVerification=true \
                /app/app.jar
          
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
            - name: dubbo
              containerPort: 18080
            - name: management
              containerPort: 9090
          volumeMounts:
            - name: linkx-encryptor-service-headshot-store
              mountPath: /home/linkx/headshot/
            - name: linkx-encryptor-service-log-store
              mountPath: /home/ubp/log_store/
            - name: linkx-encryptor-service-jingxin-file
              mountPath: /home/linkx/file/
            - name: linkx-encryptor-service-mapbox-store
              mountPath: /home/ics/offlinemap/data
            - name: oom-dump
              mountPath: /opt/dump/
          readinessProbe:
            httpGet:
              path: /actuator
              port: 9090
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 20
          livenessProbe:
            httpGet:
              path: /actuator
              port: 9090
            initialDelaySeconds: 15
            periodSeconds: 5
            failureThreshold: 20
          envFrom:
            - configMapRef:
                name: cloudcmd-profile
            - configMapRef:
                name: linkx-encryptor-config
          env:
            - name: cloudcmd.service.name
              value: linkx-encryptor-service
            - name: ENV
              value: prod
            - name: SERVER_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: pod.ip
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
      restartPolicy: Always
  selector:
    matchLabels:
      app: linkx-encryptor-service